# Default properties (can be overridden by profiles)
quarkus:
  application:
    name: multi-tenant-app
    version: 1.0.0-SNAPSHOT

  # Default Datasource (PostgreSQL) - to be overridden by profiles
  datasource:
    db-kind: postgresql
    username: default_user
    password: default_password
    jdbc:
      url: jdbc:postgresql://localhost:5432/default_db
  flyway:
    migrate-at-start: true

  # Default OIDC settings - to be overridden by profiles
  oidc:
    auth-server-url: https://default-auth-server/realms/default_realm
    client-id: default_client
    # credentials:
    #   secret: default_secret # Avoid storing secrets directly if possible, use Vault/env vars

# --- DEV Profile ---
"%dev":
  quarkus:
    log:
      level: INFO
      category:
        "org.example.multi_tenant_app": DEBUG
    datasource:
      username: dev_user
      password: dev_password
      jdbc:
        url: jdbc:postgresql://localhost:5432/dev_db
    oidc:
      auth-server-url: https://dev-auth-server/realms/dev_realm
      client-id: dev_client
  # Example custom property for dev
  custom:
    feature:
      enabled: true

# --- SIT Profile ---
"%sit":
  quarkus:
    log:
      level: INFO
    datasource:
      username: sit_user
      # password: Use environment variables or Vault for SIT passwords
      jdbc:
        url: jdbc:postgresql://sit-db-server:5432/sit_db
    oidc:
      auth-server-url: https://sit-auth-server/realms/sit_realm
      client-id: sit_client
  custom:
    feature:
      enabled: true

# --- PRE-PROD Profile ---
"%pre-prod":
  quarkus:
    log:
      level: WARN
    datasource:
      username: preprod_user
      # password: Use environment variables or Vault for PRE-PROD passwords
      jdbc:
        url: jdbc:postgresql://preprod-db-server:5432/preprod_db
    oidc:
      auth-server-url: https://preprod-auth-server/realms/preprod_realm
      client-id: preprod_client
  custom:
    feature:
      enabled: false # Example: feature disabled in pre-prod

# --- PROD Profile ---
"%prod":
  quarkus:
    log:
      level: ERROR
    # Production datasource should ideally use Vault or environment variables for credentials
    datasource:
      username: prod_user
      # password: SET_VIA_ENV_OR_VAULT
      jdbc:
        url: jdbc:postgresql://prod-db-server:5432/prod_db
    flyway:
      migrate-at-start: false # Consider manual control for prod migrations
    oidc:
      auth-server-url: https://prod-auth-server/realms/prod_realm
      client-id: prod_client
  custom:
    feature:
      enabled: false

# Example of a common property that might not change per profile
greeting:
  message: "hello from multi-tenant-app"
